basic:
    name: 'NGA National Gallery of Art T0'
    environments:
        production: 'https://www.nga.gov/'
        staging: 'https://drupal-test.nga.gov/'
        development: 'https://drupal-dev.nga.gov'
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: admin, password: ngaRules }
        development: { user: admin, password: ngaRules }
    breakpoints:
        - 390
        - 770
        - 1440
    pages:
        - /
        - /artle
        - /artvibes
        - /artvibes-results/Lazy/Groove/Chirp
        - /artwork-search
        - '/artwork-search?keywords=Mark%20Rothko&images=1&f%5B%5D=awtype:107231'
        - /search
        - "/search?keywords=Ginevra%20de'%20Benci%20%5Bobverse%5D&type%5B%5D=artwork"
        - /our-artworks/free-images-and-open-access
        - /visit
        - /exhibitions/paris-1874-impressionist-moment
    monitoring:
        days: [Mon, Fri, Tue, Wed, Thu]
        type: weekly
        schedule_time: '04:00 AM'
        schedule_time_zone: America/Los_Angeles
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 40
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: '15'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
